[build-system]
requires = ["setuptools>=64.0"]
build-backend = "setuptools.build_meta"

# Project metadata
[project]
name = "glycowork"
version = "1.10.0"
description = "Package for processing and analyzing glycans"
readme = "README.md"
authors = [
    {name = "Daniel Bojar", email = "daniel.bojar@gu.se"}
]
keywords = ["glycans", "glycomics", "glycobiology", "bioinformatics", "machine learning"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Operating System :: OS Independent"
]
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "matplotlib",
    "scikit-learn",
    "networkx>=3.0",
    "statsmodels",
    "scipy>=1.16",
    "seaborn",
    "bokeh",
    "IPython",
    "pandas>=2.1",
    "drawSvg~=2.0",
    "openpyxl",
    "glycorender[png]~=0.3.1"
]

[project.urls]
Homepage = "https://github.com/BojarLab/glycowork"
Documentation = "https://bojarlab.github.io/glycowork/"
Changelog = "https://github.com/BojarLab/glycowork/blob/master/CHANGELOG.md"
Issues = "https://github.com/BojarLab/glycowork/issues"

[project.optional-dependencies]
ml = ["torch_geometric", "torch", "xgboost", "huggingface_hub>=0.16.0"]
chem = ["glyles~=1.2.3a0", "pubchempy", "requests", "py3Dmol"]
all = ["glycowork[ml,chem]"]
dev = ["glycowork[all]", "nbdev", "pytest", "glycontact>=0.3.3"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["glycowork*"]
exclude = ["index_files*"]

[tool.setuptools.package-data]
"*" = ["*.csv", "*.pkl", "*.jpg", "*.pt", "*.json"]

[tool.nbdev]
lib_path = "glycowork"
lib_name = "glycowork"
doc_path = "_docs"
nbs_path = "."
recursive = false
tst_flags = "slow"
repo_name = "glycowork"
branch = "master"
git_url = "https://github.com/BojarLab/glycowork/tree/master/"
custom_sidebar = false
doc_host = "https://BojarLab.github.io"
doc_baseurl = "/glycowork/"
title = "glycowork"
description = "Package for processing and analyzing glycans"