# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = ["glycan_data.py"]

doc_url = "https://BojarLab.github.io/glycowork/"

git_url = "https://github.com/BojarLab/glycowork"

def custom_doc_links(name): return None
