# AUTOGENERATED! DO NOT EDIT! File to edit: ../04_network.ipynb.

# %% auto 0
__all__ = ['human_skin_O_PMC5871710_BCC']

# %% ../04_network.ipynb 2
from .glycan_data.loader import glycomics_data_loader
human_skin_O_PMC5871710_BCC = glycomics_data_loader.human_skin_O_PMC5871710_BCC
from .network.biosynthesis import *
from .network.evolution import *
